using Raylib_cs;
using rlImGui_cs;

namespace Shoko;

class Program
{
    static void Main(string[] args)
    {
        Raylib.SetConfigFlags(
            ConfigFlags.FLAG_MSAA_4X_HINT |
            ConfigFlags.FLAG_WINDOW_HIGHDPI |
            ConfigFlags.FLAG_WINDOW_MAXIMIZED |
            ConfigFlags.FLAG_WINDOW_RESIZABLE |
            ConfigFlags.FLAG_VSYNC_HINT);
        Raylib.InitWindow(0, 0, "Shoko");

        rlImGui.BeginInitImGui();
        bool quit = MainUI.Load(args);
        rlImGui.EndInitImGui();

        while(!Raylib.WindowShouldClose() && quit)
        {
            Raylib.BeginDrawing();
            Raylib.ClearBackground(Color.WHITE);
            rlImGui.Begin();

            quit = MainUI.Render();

            rlImGui.End();
            Raylib.EndDrawing();
        }
        rlImGui.Shutdown();
        Raylib.CloseWindow();
    }
}